apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test-gogog
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:azure-7ee9dc3a396e1d6e7494b619e1f3e3d06cd23595
          name: container-image
